### ISSUE TITLE
Default value for config

### ISSUE THREAD

**Issue by carbonin** [slemrmartin/mock_collector#1]
https://github.com/slemrmartin/mock_collector/blob/2014009a61acc0da358c99a3dd78b5a3af7b934b/bin/openshift-mock-collector#L27
It looks like we require a value to be set if the env var is nil even though we have a hard-coded default.

Also, why isn't the "default" config file the default value?

**Comment by slemrmartin** [comment]
@carbonin good idea! 
Simply this file was created before the default config came in my mind :)
https://github.com/slemrmartin/mock_collector/commit/027e98e478cdfab133cce48cce02baf1911b095f
